---
title: "Chris cleaning + figures"
author: "Lauren Stiles"
date: "2023-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load libraries
```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(janitor)
library(vegan)
library(here)
library(ggforce)
library(concaveman)
library(ggrepel)
library(RColorBrewer)
library(ggsci)


```

#load tables
```{r, message = FALSE}
inv2018csv <- read.csv(here("tables/2018_raw_normalized.csv"), skip = 5) #2019 already in #/liter

inv2019csv <- read_csv(here("tables/2019_normalized.csv"), skip = 1) #already in #/liter 

inv2020_22csv <- read_csv(here("tables/2021_raw_updated1.csv")) #needs to be converted into #/liter
```

#reformat year tables to match
```{r}
#clean up 2018 #/liter data 
inv2018 <- inv2018csv |>
  clean_names() |>                                  #make names lower case 
  select(1:42, -4) |>                               #remove blank columns 
  #filter(!is.na(date_1)) |>                        #keep only the rows with dates
  select(1:3, ends_with("_number_liter")) |>        #keep column names with #/liter, don't need raw counts
  rename_with(~ gsub("_number_liter", "", .x))      #rename #/liter columns to just invert type, gsub is operation to replace -- not sure what the ~ and . before the x does ??

#clean up 2019 #/liter data 
inv2019 <- inv2019csv |> 
  clean_names() |>                                      #make all names lower case 
  select(1:42, -4) |>                                   #remove blank columns 
  filter(!is.na(date_1), !is.na(site_2)) |>             #keep only the rows with dates and sites 
  mutate(across(ostracod:total_number, ~as.numeric(.)), #make values numeric
         date_1 = dmy(date_1)) |>                       #format date 
  rename(date = date_1,
         site = site_2,
         sample_type = sample_type_3) |> #rename columns, renaming ephemeroptera makes it match 2019 column names so the two data frames can be combined   
  select(-total_number) #remove this column because 2020_22 does not have it...


#clean the 2021 and 2022 data (on same sheet) 
inv2020_22 <- inv2020_22csv |>
  clean_names() |>                                    #make column names all lowercase 
  select(-person_entering_data, 
         -person_that_sorted_the_sample, 
         -lepidoptera_crambidae,
         -hemiptera_mesoveliidae,
         -coleoptera_tropiscernus,
         -plecoptera_sp,
         -mollusk, 
         -syrphidae,
         -terrestrials,
         -hydrachnidia, 
         -isopod, 
         -larvae,
         -comments, 
         -x57, 
         -unknown, 
         -total_number, 
         -ephemeroptera) |>           #remove unnecessary columns and those that don't match 2019 
  mutate(across(ostracod:clam_shrimp, ~replace_na(.,0)),   #replace NA's with zeroes
         across(ostracod:clam_shrimp, ~.x/70),             # convert to organisms/L 
         #if you want to use early 2021 data, have to figure out how to split because of scoop difference 
         across(ostracod:clam_shrimp, ~as.numeric(.)),     # make numeric
         date_on_vial = dmy(date_on_vial)) |>         # format date
  rename(date = date_on_vial) #rename columns 
```


# combine 2019 and 2020-22
```{r}
inv2019_22 <- bind_rows(inv2020_22, inv2019) |> #combine 2019 with 2020-2022 data, this function adds rows
              select(-coleoptera_total, 
                     -annelida_total, 
                     -hemiptera_total, 
                     -diptera_total) #remove these cause they are already accounted for by invert columns for individual taxa 

```

#clean FB250 data 
```{r}
#filtering for only one method
fb250 <- inv2019_22 |>  
         filter(sample_type == "FB250" |
                sample_type == "FB 250") #filter for FB250 method, accounting for typos 

#want to be able to compare seasons (quarters) and years 
fb250date <- fb250 |>
  mutate(season = quarter(date, with_year = TRUE)) |> #new column with dates accounting for quarters
  unite("datesite", c("season", "site"), sep = "|") #make new column combining year, quarter, and site 
  #will be useful for making NMDS matrix later 

fb250formatted <- fb250date |> 
  select(-date, -sample_type) |>                #remove date column in old format 
  group_by(datesite) |>                         #group by datesite so averages works 
  summarize(across(where(is.numeric), mean)) |> #take average of duplicate datesite rows 
  ungroup() |>                                  #ungroup 
  select(-tipulidae_larva, 
         -coleoptera_dytiscidae_agabus, 
         -coleoptera_dytiscidae_colymbetinae,
         -coleoptera_curculionidae_weavil) |>  #each of these columns added up to 0 
  mutate(across(ostracod:clam_shrimp, ~.x*1000)) |> #multiply all values by 1000 because NMDS does not like such small numbers
  column_to_rownames("datesite") 

check <- as.data.frame(rowSums(fb250formatted)) |> #take sums of rows in fb250 formatted, matters because NMDS does like rows that add up to 0 
  rename(sum = "rowSums(fb250formatted)") |> #rename column to make prettier 
  filter(sum != 0) |>                        #filter out rows that have sum of 0 
  rownames_to_column("datesite")             #bring datesite back to columns...? why? 


fb250formatted_sum <- fb250date |> #format with invert sum column 
  select(-date, -sample_type) |>                #remove date column in old format 
  group_by(datesite) |>                         #group by datesite so averages works 
  summarize(across(where(is.numeric), mean)) |> #take average of duplicate datesite rows 
  ungroup() |>                                  #ungroup 
  select(-tipulidae_larva, 
         -coleoptera_dytiscidae_agabus, 
         -coleoptera_dytiscidae_colymbetinae,
         -coleoptera_curculionidae_weavil) |>  #each of these columns added up to 0 
  mutate(across(ostracod:clam_shrimp, ~.x*1000)) |> #multiply all values by 1000 because NMDS does not like such small numbers
  right_join(check, by = "datesite") |> 
  separate(datesite, c("date", "site"), sep = "[|]", remove = FALSE)|> 
  separate(date, c ("year", "season"), sep = "[.]")


#format fb250date data frame 
fb250formatted_NMDS <- fb250date |>   #the purpose of this additional data frame is to remove rows with a sum of 0 for the NMDS 
  select(-date, -sample_type) |>                #remove date column in old format 
  group_by(datesite) |>                         #group by datesite so averages works 
  summarize(across(where(is.numeric), mean)) |> #take average of duplicate datesite rows 
  ungroup() |>                                  #ungroup 
  select(-tipulidae_larva, 
         -coleoptera_dytiscidae_agabus, 
         -coleoptera_dytiscidae_colymbetinae,
         -coleoptera_curculionidae_weavil) |>  #each of these columns added up to 0 
  mutate(across(ostracod:clam_shrimp, ~.x*1000)) |> #multiply all values by 1000 because NMDS does not like such small numbers
  right_join(check, by = "datesite") |> 
  filter(sum != "0") |> 
  select(-sum) |> 
  column_to_rownames("datesite")   #put datesite back as a rowname 


#create reference df with site information 
site_df <- fb250formatted |> 
           rownames_to_column("sites") |>      #put back to column named "sites"
           select(sites) |>                    #select only sites column 
           separate(sites, c("date", "site"), sep = "[|]", remove = FALSE)|> #separate date and site
           separate(date, c ("year", "season"), sep = "[.]", remove = FALSE) |> #separate year and season   
           unite("qtrsite", c("season", "site"), sep = ".", remove = FALSE)
            
           
#what to do with duplicate date-site combinations?  -- decided to average them...       
unique(fb250date$datesite)  # about 60 duplicates  

#3/06: we still need to know whether previous people used 7.5 liters or what....

site_color <- fb250formatted |> 
              rownames_to_column("sites") |>      #put back to column named "sites"
              select(sites) |>                    #select only sites column 
              separate(sites, c("date", "site"), sep = "[|]", remove = FALSE)|> #separate date and site
              separate(date, c ("year", "season"), sep = "[.]")
              

```


#histograms to see distribution 
```{r}

hist(fb250formatted_sum$sum) #looking at distribution of sums, does not look normal, looks right skewed  

hist(fb250formatted_sum$cladocera) #also looks right skewed 

hist(fb250formatted_sum$copepod) #also looks right skewed 

hist(fb250formatted_sum$ostracod) #also looks right skewed 

hist(fb250formatted_sum$hemiptera_corixidae_boatman) #also looks right skewed

```


#try NMDS
```{r}
#make new data frame selecting 2019 and 2022 and overlapping sites in both NCOS and COPR using data frame previously formatted to NMDS -- make sure to get it back to same format to run NMDS
fb250_NMDS_19_22 <- fb250formatted_NMDS |> 
                    rownames_to_column("sites") |>
                    separate(sites, c("date", "site"), sep = "[|]", remove = FALSE) |> #separate date and site
                    separate(date, c ("year", "season"), sep = "[.]") |>
                    filter(year %in% c("2019", "2022") & 
                    site %in% c("NDC", "NEC","NPB", "NPB1", "NVBR", "NWP", "NWC", "NMC", "NPB2","CUL1", "MO1")) |> 
                    select(-year, -season, -site) |> 
                    column_to_rownames("sites") |> 
                    select(-clam_shrimp, -trichoptera_sp, -coleoptera_gyrindae_gyrinini, -coleoptera_dytiscidae_liodessus_affinis) #removed more columns that add up to 0

#make NMDS that shows years and sites 
fb250_NMDS <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 2) #stress .25...

stressplot(fb250_NMDS) #nonmetric R2 = 0.942, linear fit R2 = 0.697

plot(fb250_NMDS) 

plot_df <- scores(fb250_NMDS, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019", "2022") & 
                    site %in% c("NDC", "NEC","NPB", "NVBR", "CUL1","MO1")) #ask alison about which sites to choose !!
  
plot_df
#2022.2 NWP does not have values 

plot_nmds <- ggplot(plot_df, aes(x = NMDS1, y = NMDS2, color = year, shape = site)) +
  geom_point(size = 3, alpha = 0.8) +
  stat_ellipse(linetype = 2, size = 1) +
  labs(title = "NMDS")
plot_nmds
#need more 2022 data here! check samples babyyy!!



#another NMDS but this time the sites covered are COPR sites, also goes over years ------------------------------------------
fb250_NMDS1 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .25...

stressplot(fb250_NMDS1) #nonmetric R2 = 0.942, linear fit R2 = 0.697

plot(fb250_NMDS1) 

plot_df1 <- scores(fb250_NMDS1, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019", "2022") & 
                    site %in% c("NDC","MO1")) #ask alison about which sites to choose 
plot_df1
#2022.2 NWP does not have values 

plot_nmds1 <- ggplot(plot_df1, aes(x = NMDS1, y = NMDS2, color = site, shape = year)) +
  geom_point(size = 3, alpha = 0.8) +
  #stat_ellipse(linetype = 2, size = 1) +
  labs(title = "NMDS") +
  geom_mark_hull(aes(fill = year, label = site))
plot_nmds1 #sooo greater distance between years at MO1 perhaps...also need to do the ellipse thing 
#so this one does not really work-- maybe too much to have both sites and years 




#another NMDS with NCOS sites, just looking at years  -------------------------------------------------------------------
fb250_NMDS2 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .16 when k = 3 ...

stressplot(fb250_NMDS2) #nonmetric R2 = 0.974, linear fit R2 = 0.801 when k = 3 

plot(fb250_NMDS2) 

plot_df2  <- scores(fb250_NMDS2, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019","2022") &
         site %in% c("NDC", "NEC","NPB", "NPB1", "NVBR", "NWP", "NWC", "NMC", "NPB2")) 
plot_df2
#2022.2 NWP does not have values 


plot_nmds2 <- ggplot(plot_df2, aes(x = NMDS1, y = NMDS2, color = year, shape = year)) +
  geom_point(size = 3.2, alpha = 1) +
  geom_mark_hull(aes(fill = year), alpha = 0.5) + 
  ggrepel::geom_text_repel(data = plot_df2, aes(x=NMDS1, y=NMDS2, label = qtrsite), 
                           cex = 3, direction = "both", 
                           segment.size = 0.25) + 
  
  scale_color_manual(values = c("darkgoldenrod1", "steelblue")) +
  scale_fill_manual(values = c("darkgoldenrod1", "steelblue")) +
  
  #scale_fill_aaas() +
  #scale_color_aaas() +
  
  theme_bw() + 
        theme(axis.text.x = element_blank(),  # remove x-axis text
              axis.text.y = element_blank(), # remove y-axis text
              axis.ticks = element_blank(),  # remove axis ticks
              axis.title.x = element_text(size = 20), # size x-axis labels
              axis.title.y = element_text(size = 20), # size y-axis labels 
              legend.title = element_text(size = 20), 
              legend.text = element_text(size = 20),
              legend.position = "bottom",
              panel.background = element_blank(), 
              panel.grid.major = element_blank(),  #remove major-grid labels
              panel.grid.minor = element_blank(),  #remove minor-grid labels
              plot.background = element_blank(), 
              plot.title = element_text(size = 20)) + 
    ylim(-2,2) +
    xlim(-2,2) + 
    labs(title = "Ordination with NCOS sites")
  
plot_nmds2 





#Another NMDS with COPR sites, just looking at years  -------------------------------------------------------------------
fb250_NMDS3 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .16 when k = 3 ...

stressplot(fb250_NMDS3) #nonmetric R2 = 0.974, linear fit R2 = 0.801 when k = 3 

plot(fb250_NMDS3) 

plot_df3  <- scores(fb250_NMDS3, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019","2022") &
         site %in% c("CUL1", "MO1"))
plot_df3


plot_nmds3 <- ggplot(plot_df3, aes(x = NMDS1, y = NMDS2, color = year, shape = year)) +
   #geom_text(data = plot_df3, aes(x = NMDS1, y = NMDS2, label = site), nudge_x = 0.2, alpha = 0.5) +
  geom_point(size = 3, alpha = 1) +
  scale_color_manual(values = c("darkgoldenrod1", "steelblue")) +
  scale_fill_manual(values = c("darkgoldenrod1", "steelblue")) +
  ylim(-2,2) +
  xlim(-2,2.5) +
  geom_mark_hull(aes(fill = year), alpha = 0.5) +
  theme_bw() + 
        theme(axis.text.x = element_blank(),  # remove x-axis text
              axis.text.y = element_blank(), # remove y-axis text
              axis.ticks = element_blank(),  # remove axis ticks
              axis.title.x = element_text(size = 20), # size x-axis labels
              axis.title.y = element_text(size = 20), # size y-axis labels 
              legend.title = element_text(size = 20), 
              legend.text = element_text(size = 20),
              legend.position = "bottom",
              panel.background = element_blank(), 
              panel.grid.major = element_blank(),  #remove major-grid labels
              panel.grid.minor = element_blank(),  #remove minor-grid labels
              plot.background = element_blank(), 
              plot.title = element_text(size = 20)) + 
  ggrepel::geom_text_repel(data = plot_df3, aes(x=NMDS1, y=NMDS2, label = qtrsite), 
                           cex = 3, direction = "both", 
                           segment.size = 0.25) + 
  labs(title = "Ordination with COPR sites")

plot_nmds3 

#Another NMDS with NCOS AND COPR sites, just looking at years  -------------------------------------------------------------------
fb250_NMDS4 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .16 when k = 3 ...

stressplot(fb250_NMDS4) #nonmetric R2 = 0.974, linear fit R2 = 0.801 when k = 3 

plot(fb250_NMDS4) 

plot_df4  <- scores(fb250_NMDS4, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019","2022") &
         site %in% c("CUL1", "MO1","NDC", "NEC","NPB", "NPB1", "NVBR", "NWP", "NWC", "NMC", "NPB2")) #"CUL1", "MO1"
plot_df4


plot_nmds4 <- ggplot(plot_df4, aes(x = NMDS1, y = NMDS2, color = year, shape = year)) +
   geom_text(data = plot_df4, aes(x = NMDS1, y = NMDS2, label = site), nudge_x = 0.2, alpha = 0.5) +
  geom_point(size = 3, alpha = 0.8) +
  ylim(-2,2) +
  xlim(-3,2) +
  geom_mark_hull(aes(fill = year)) +
  theme_bw() + 
        theme(axis.text.x = element_blank(),  # remove x-axis text
              axis.text.y = element_blank(), # remove y-axis text
              axis.ticks = element_blank(),  # remove axis ticks
              axis.title.x = element_text(size = 10), # size x-axis labels
              axis.title.y = element_text(size = 10), # size y-axis labels 
              legend.title = element_text(size = 10), 
              legend.position = "bottom",
              panel.background = element_blank(), 
              panel.grid.major = element_blank(),  #remove major-grid labels
              panel.grid.minor = element_blank(),  #remove minor-grid labels
              plot.background = element_blank())
plot_nmds4 

#Another NMDS with NCOS sites, adding SPECIES VECTORS   -------------------------------------------------------------------
fb250_NMDS5 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .16 when k = 3 ...

fb250_taxafit <- envfit(fb250_NMDS5, fb250_NMDS_19_22, permutations = 999) #use envfit to start process of making species vectors

fb250_taxaframe <- as.data.frame(scores(fb250_taxafit, display = "vectors")) |> #make data frame with species intrinsic values 
                   cbind(Taxa = rownames(fb250_taxaframe)) |> #add column with taxa names 
                   cbind(pval = fb250_taxafit$vectors$pvals) #add column with p-values so we can select taxa which are significant 

sig_taxaframe <- subset(fb250_taxaframe, pval<=0.05) #subset significant taxa 

stressplot(fb250_NMDS5) #nonmetric R2 = 0.974, linear fit R2 = 0.801 when k = 3 

plot(fb250_NMDS5) 

plot_df5  <- scores(fb250_NMDS5, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019","2022") &
         site %in% c("NDC", "NEC","NPB", "NPB1", "NVBR", "NWP", "NWC", "NMC", "NPB2"))
plot_df5


plot_nmds5 <- ggplot() +
  geom_text(data = plot_df5, aes(x = NMDS1, y = NMDS2, label = site),nudge_x = 0.2 , alpha = 0.5) +
  geom_point (plot_df5, mapping = aes(x = NMDS1, y = NMDS2, color = year, shape = year), size = 3, alpha = 0.8) +
  ylim(-2,2) +
  xlim(-3,2) +
  geom_mark_hull(plot_df5, mapping = aes(x = NMDS1, y = NMDS2, fill = year)) +
  theme_bw() + 
        theme(axis.text.x = element_blank(),  # remove x-axis text
              axis.text.y = element_blank(), # remove y-axis text
              axis.ticks = element_blank(),  # remove axis ticks
              axis.title.x = element_text(size = 10), # size x-axis labels
              axis.title.y = element_text(size = 10), # size y-axis labels 
              legend.title = element_text(size = 10), 
              legend.position = "bottom",
              panel.background = element_blank(), 
              panel.grid.major = element_blank(),  #remove major-grid labels
              panel.grid.minor = element_blank(),  #remove minor-grid labels
              plot.background = element_blank()) 

plot_nmds5 + 
  geom_segment(data = sig_taxaframe, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), 
                 arrow = arrow(length = unit(0.25, "cm")),
                 colour = "grey10", 
                 lwd = 0.3) + #add vector arrows of significant species, lwd changes line width 
  
   ggrepel::geom_text_repel(data = sig_taxaframe, aes(x=NMDS1, y=NMDS2, label = Taxa), 
                           cex = 3, direction = "both", 
                           segment.size = 0.25) + #add labels for species, use ggrepel::geom_text_repel so that labels do not overlap
  labs(title = "Ordination with species vectors")

plot_nmds5 

#Another NMDS with COPR sites, adding SPECIES VECTORS   -------------------------------------------------------------------
fb250_NMDS6 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .16 when k = 3 ...

fb250_taxafit <- envfit(fb250_NMDS6, fb250_NMDS_19_22, permutations = 999) #use envfit to start process of making species vectors


fb250_taxaframe <- as.data.frame(scores(fb250_taxafit, display = "vectors")) |> #make data frame with species intrinsic values 
                   cbind(Taxa = rownames(fb250_taxaframe)) |> #add column with taxa names 
                   cbind(pval = fb250_taxafit$vectors$pvals) #add column with p-values so we can select taxa which are significant 

sig_taxaframe <- subset(fb250_taxaframe, pval<=0.05) #subset significant taxa 

stressplot(fb250_NMDS5) #nonmetric R2 = 0.974, linear fit R2 = 0.801 when k = 3 

plot(fb250_NMDS5) 

plot_df6  <- scores(fb250_NMDS6, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019","2022") &
         site %in% c("CUL1", "MO1"))
plot_df5


plot_nmds6 <- ggplot() +
  geom_text(data = plot_df6, aes(x = NMDS1, y = NMDS2, label = site, nudge_x = 0.2, alpha = 0.5) +
  geom_point (plot_df6, mapping = aes(x = NMDS1, y = NMDS2, color = year, shape = year), size = 3, alpha = 0.8) +
  ylim(-2,2) +
  xlim(-3,2) +
  geom_mark_hull(plot_df6, mapping = aes(x = NMDS1, y = NMDS2, fill = year)) +
  theme_bw() + 
        theme(axis.text.x = element_blank(),  # remove x-axis text
              axis.text.y = element_blank(), # remove y-axis text
              axis.ticks = element_blank(),  # remove axis ticks
              axis.title.x = element_text(size = 10), # size x-axis labels
              axis.title.y = element_text(size = 10), # size y-axis labels 
              legend.title = element_text(size = 10), 
              legend.position = "bottom",
              panel.background = element_blank(), 
              panel.grid.major = element_blank(),  #remove major-grid labels
              panel.grid.minor = element_blank(),  #remove minor-grid labels
              plot.background = element_blank()) 

plot_nmds6 + 
  geom_segment(data = sig_taxaframe, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), 
                 arrow = arrow(length = unit(0.25, "cm")),
                 colour = "grey10", 
                 lwd = 0.3) + #add vector arrows of significant species, lwd changes line width 
  
   ggrepel::geom_text_repel(data = sig_taxaframe, aes(x=NMDS1, y=NMDS2, label = Taxa), 
                           cex = 3, direction = "both", 
                           segment.size = 0.25) + #add labels for species, use ggrepel::geom_text_repel so that labels do not overlap
  labs(title = "Ordination with species vectors")

plot_nmds6


#ANOTHER NMDS THIS TIME LOOKING AT SEASONS ----------

fb250_NMDS7 <- metaMDS(fb250_NMDS_19_22, distance = "bray", k = 3) #stress .16 when k = 3 ...

stressplot(fb250_NMDS7) #nonmetric R2 = 0.974, linear fit R2 = 0.801 when k = 3 

plot(fb250_NMDS7) 

plot_df7  <- scores(fb250_NMDS7, display = "sites") %>% 
  as.data.frame() %>% #takes scores from NMDS and making coordinates into a data frame/tibble
  rownames_to_column("sites") %>% 
  full_join(site_df, by = "sites") |> 
  filter(year %in% c("2019","2022") &
         site %in% c("NDC", "NEC","NPB", "NPB1", "NVBR", "NWP", "NWC", "NMC", "NPB2")) #"CUL1", "MO1"
   #ordiplot(fb250_NMDS2, type="n")
plot_df7
#2022.2 NWP does not have values 

plot_nmds7 <- ggplot(plot_df7, aes(x = NMDS1, y = NMDS2, color = season, shape = season)) +
  geom_point(size = 3.2, alpha = 1) +
  ylim(-2,2) +
  xlim(-2,2) +
  geom_mark_hull(aes(fill = season), alpha = 0.5) + 
  scale_colour_manual(values = c("2019" = "red", "2022" = "blue")) +
  ggrepel::geom_text_repel(data = plot_df2, aes(x=NMDS1, y=NMDS2, label = qtrsite), 
                           cex = 3, direction = "both", 
                           segment.size = 0.25) + 
  theme_bw() + 
        theme(axis.text.x = element_blank(),  # remove x-axis text
              axis.text.y = element_blank(), # remove y-axis text
              axis.ticks = element_blank(),  # remove axis ticks
              axis.title.x = element_text(size = 10), # size x-axis labels
              axis.title.y = element_text(size = 10), # size y-axis labels 
              legend.title = element_text(size = 10), 
              legend.position = "bottom",
              panel.background = element_blank(), 
              panel.grid.major = element_blank(),  #remove major-grid labels
              panel.grid.minor = element_blank(),  #remove minor-grid labels
              plot.background = element_blank())
  
plot_nmds7 

```

